---
- name: "Battle-Station Builder"
  hosts: localhost
  connection: local
  roles:
    - role: "roles/install-tools"
    - role: "roles/customize-terminal"
    - role: "roles/customize-browser"
    - role: "roles/configure-logging"
    - role: "roles/configure-system"
    - role: "gantsign.visual-studio-code"